spring:
  application:
    name: bg 
  profiles:
    active: dev
  data:
    rest:
      basePath: /api2   
    admin:
      basePath: /admin2   
  jackson:
    serialization:
      fail-on-empty-beans: false
 
    
server:
  port: 80
   
---

spring:
  profiles: dev
  jpa:    
     show-sql: true    
  
app:
  db: 
    url: jdbc:mariadb://172.21.208.1:3306/databasebg5?user=root&password=bg&useSSL=false&allowPublicKeyRetrieval=true
  ldap: 
    active: false  
    url: ldap://localhost:10389/dc=agr82,dc=com  
  client:
    url: http://localhost:4200
  
logging:
  level: 
    root: info

---

spring:
  profiles: aws
  jpa:    
     show-sql: true    
  
app:
  db: 
    url: jdbc:mariadb://database-1.csfuhimiizmi.eu-west-3.rds.amazonaws.com:3306?user=admin&password=Montpezat&useSSL=false&allowPublicKeyRetrieval=true
  ldap: 
    active: false  
    url: ldap://localhost:10389/dc=agr82,dc=com  
  client:
    url: http://localhost:4200
  
logging:
  level: 
    root: info


   
  